" Dependencies you might want to install
" $ sudo apt-get install vim-gui-common
" $ sudo apt-get install vim-runtime


set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')
"
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" VIM Visual theme
Plugin 'tomasr/molokai'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


set nu                " Show line numbers
set linebreak         " Break lines at word
set showbreak=+++     " Wrap-broken line prefix
set showmatch         " Highlight matching brace
set visualbell        " Use visual bell (no beeping)
set nospell             " Enable spell-checking
set noerrorbells      " no bells in terminal

set hlsearch        " Highlight all search results
set smartcase       " Enable smart-case search
set ignorecase      " Always case-insensitive
set incsearch       " Incremental search
set wrapscan

set softtabstop=2
set tabstop=2
set shiftwidth=2
set textwidth=80    " Line wrap (number of columns)
set expandtab
set backspace=2


" this should get best indenting for most common filetypes
filetype on
filetype indent plugin on
set autoindent
set smartindent

" display
set scrolloff=5               " scroll offset, min lines above/below cursor
set scrolljump=5              " jump 5 lines when running out of the screen
set sidescroll=10             " minimum columns to scroll horizontally
set showcmd                   " show command status
set showmatch                 " flashes matching paren when one is typed
set showmode                  " show editing mode in status (-- INSERT --)
set ruler                     " show cursor position

" Advanced
set ruler
set undolevels=1000   " number of undos stored
set viminfo='50,"50   " '=marks for x files, "=registers for x files
set backspace=indent,eol,start
set autowriteall      " Auto write all changes

" Keep some stuff in the history
set history=1000

" Automatically read a file that has changed on disk
set autoread

" Highlight the current line and column
set nocursorline
set nocursorcolumn

" Highlight unwanted spaces
let c_space_errors=1

" Enable 80 column line
set colorcolumn=+1
set colorcolumn=+1,+2
highlight ColorColumn ctermbg=darkgrey guibg=darkgrey

" Remember last position of cursor in a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" enable color syntax highlighting
syntax on
